if (self.CavalryLogger) { CavalryLogger.start_js(["J91uobw"]); }

__d("useCometWindowSize",["CometThrottle","react","useCometPassiveWindowSize"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useEffect,i=b.useState;function a(a){a===void 0&&(a=500);var b=c("useCometPassiveWindowSize")(),d=b.getCurrent();d=i(d);var e=d[0],f=d[1];h(function(){var d=c("CometThrottle")(function(){f(b.getCurrent())},a),e=b.subscribe(d);return function(){d.cancel(),e.remove()}},[b,a]);return e}g["default"]=a}),98);
__d("StoriesCreateContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=!1;c=a.createContext(b);g["default"]=c}),98);
__d("StoriesCreateConstants",["fbt"],(function(a,b,c,d,e,f,g,h){"use strict";a={DEFAULT:{BODY:h._("Are you sure you want to discard this story? Your story won't be saved."),CANCEL:h._("Continue Editing"),CONFIRM:h._("Discard"),TITLE:h._("Discard Story?")}};b={SELECTION_TILE_HEIGHT:330,SELECTION_TILE_WIDTH:220,SPACE_BETWEEN_SELECTOR:20};c={FOOTER_HEIGHT:52,HEADER_HEIGHT:16};d={COMET_PUSH_VIEW_HEIGHT:28,CONTAINER_HORIZONTAL_PADDING:24*2,CONTAINER_MAX_WIDTH:940,CONTAINER_VERTICAL_PADDING:32*2,CONTENT_HEADER_HEIGHT:36,CONTENT_HORIZONTAL_PADDING:16*2,CONTENT_VERTICAL_PADDING:16*2,MAX_OVERLAY_WIDTH:472.5,SIDE_PANE_WIDTH:360};e=h._("Start typing");f={FOOTER_HEIGHT:12,HEADER_HEIGHT:12};h={EDITING:"editing",NONE:"none"};var i={EMOJI:"emoji",LOCATION:"location",POLL:"poll",TAG:"tag"},j={EDITING:"editing",NONE:"none"},k={HORIZONTAL:"horizontal",NONE:"none"},l=26,m=3,n=4,o={FOOTER_HEIGHT:92};g.LEAVE_TEXT=a;g.NULL_STATE_DIMENSIONS=b;g.PHOTO_PREVIEW_DIMENSIONS=c;g.PREVIEW_DIMENSIONS=d;g.SATP_PLACEHOLDER=e;g.SATP_PREVIEW_DIMENSIONS=f;g.STICKER_EDITING_MODE=h;g.STICKER_TYPE=i;g.TEXT_OVERLAY_MODE=j;g.OVERLAY_ALIGNMENT_TYPE=k;g.VIDEO_MAX_DURATION=l;g.VIDEO_MIN_DURATION=m;g.VIDEO_MIN_DURATION_FOR_TRIM=n;g.VIDEO_PREVIEW_DIMENSIONS=o}),98);
__d("ManagedError",[],(function(a,b,c,d,e,f){a=function(a){babelHelpers.inheritsLoose(b,a);function b(b,c){var d;d=a.call(this,b!==null&&b!==void 0?b:"")||this;b!==null&&b!==void 0?d.message=b:d.message="";d.innerError=c;return d}return b}(babelHelpers.wrapNativeSuper(Error));f["default"]=a}),66);
__d("AssertionError",["ManagedError"],(function(a,b,c,d,e,f,g){a=function(a){babelHelpers.inheritsLoose(b,a);function b(b){return a.call(this,b)||this}return b}(c("ManagedError"));g["default"]=a}),98);
__d("Assert",["AssertionError","sprintf"],(function(a,b,c,d,e,f,g){function h(a,b){if(typeof a!=="boolean"||a===!1)throw new(c("AssertionError"))(b);return a}function i(a,b,d){var e;if(b===void 0)e="undefined";else if(b===null)e="null";else{var f=Object.prototype.toString.call(b);f=/\s(\w*)/.exec(f);e=f==null?typeof f:f[1].toLowerCase()}h(a.indexOf(e)!==-1,(f=d)!=null?f:c("sprintf")("Expression is of type %s, not %s",e,a));return b}function a(a,b,c){h(b instanceof a,(a=c)!=null?a:"Expression not instance of type");return b}function j(a,b){k["is"+a]=b,k["maybe"+a]=function(a,c){return a==null?a:b(a,c)}}b=function(a,b){return a};var k={isInstanceOf:a,isTrue:h,isTruthy:function(a,b){return h(!!a,b)},isBoolean:b,isFunction:b,isNumber:b,isObject:b,isString:b,isUndefined:b,maybeObject:b,maybeNumber:b,maybeFunction:b};["Boolean","Function","Number","Object","String","Undefined"].forEach(function(a){j(a,i.bind(null,a.toLowerCase()))});d=k;g["default"]=d}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("useCustomEqualityMemo")(a,c("shallowEqual"))}g["default"]=a}),98);
__d("useToggle",["react"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useCallback,i=b.useState;function a(a){a===void 0&&(a=!1);a=i(a);var b=a[0],c=a[1];a=h(function(a){c(a==null?function(a){return!a}:a)},[]);return[b,a]}g["default"]=a}),98);
__d("XCometGamingArenaHomeControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/gaming/tournaments/",Object.freeze({open_create_tournament_form:!1}),void 0);b=a;g["default"]=b}),98);